server:
  port: 8010
spring:
  application:
    name: student-service
  cloud:
    consul:
      discovery:
        register: true
        service-name: student-service
      host: 127.0.0.1
      port: 8500